module.exports = {
    clientDrawing: 'client-drawing',
    newMessage: 'new-message',
    errorMsg: 'error-msg',
    changeInRoom: 'changeInRoom',
    message: 'message',
    drawing: 'drawing',
    connection: 'connection',
    disconnect: 'disconnect',
    joinGame: 'joinGame',
    wordChosen: 'wordChosen',
    getDashes: 'getDashes',
    guessedSound: 'guessedSound',
    urlString: 'http://localhost:3000',
};