module.exports = {
    clientDrawing: 'client-drawing',
    newMessage: 'new-message',
    errorMsg: 'error-msg',
    changeInRoom: 'changeInRoom',
    message: 'message',
    drawing: 'drawing',
    connection: 'connection',
    disconnect: 'disconnect',
    joinGame: 'joinGame',
    startGame: 'startGame',
    wordChosen: 'wordChosen',
    getDashes: 'getDashes',
    guessedSound: 'guessedSound',
    toggleCanvas: 'toggleCanvas',
    selectAWord: 'selectAWord',
    emitSelectedWord: 'emitSelectedWord',
    turnIsOver: 'turnIsOver',
    urlString: 'http://localhost:3000'
};